### ISSUE TITLE
6.5.5-200.fc38.x86_64 on latest 5.0.1-3 repo ?

### ISSUE THREAD

**Issue by kashortiexda** [t2linux/fedora-kernel#19]
I am struggling to update the kernel only to 6.5.5-200.fc38.x86_64

On Fedora 38 - I have updated the t2linux-repo to 5.0.1-3 using latest RPM, and it is enabled. But I am not getting any dnf update from 6.4.15-200.t2.fc38.x86_64 to 6.5.5-200.fc38.x86_64 ?

What am I doing wrong ?

etc/yum.repos.d/t2linux-fedora.repo as below..

[t2linux-fedora]
name=t2linux Fedora
baseurl=https://t2linux-fedora-repo.netlify.app/
enabled=True
gpgcheck=True
cost=800
priority=80
gpgkey=file:///etc/pki/rpm-gpg/t2linux-fedora.pub

The PGP keys are correct

**Comment by sharpenedblade** [comment]
its not in the repo yet, im working on fixing it

**Comment by sharpenedblade** [comment]
Its fixed now

**Comment by kashortiexda** [comment]
> Its fixed now

Still not updating with sudo dnf upgrade. I reloaded the repo.

**Comment by kashortiexda** [comment]
@sharpenedblade please assist me, I just cannot seem to be able to install 6.5.5 (manually) or upgrading with repo dnf update/upgrade.
How can I install this kernel on Fedora ?

**Comment by sharpenedblade** [comment]
Try again now, it was working for me. DNF caches the metadata for a while.

**Comment by kashortiexda** [comment]
After "sudo dnf upgrade --refresh" it finds the t2linux kernel now but it gives a GPG check FAILED

I am on Fedora 39beta 
(uname -r gives me 6.4.15-200.t2.fc38.x86_64)
How can I get the kernel to update for 39beta to 6.5.5-200

Package kernel-core-6.5.5-200.t2.fc38.x86_64.rpm is not signed
Package kernel-devel-6.5.5-200.t2.fc38.x86_64.rpm is not signed
Package kernel-modules-6.5.5-200.t2.fc38.x86_64.rpm is not signed
Package kernel-modules-core-6.5.5-200.t2.fc38.x86_64.rpm is not signed
Package kernel-modules-extra-6.5.5-200.t2.fc38.x86_64.rpm is not signed
Package kernel-modules-internal-6.5.5-200.t2.fc38.x86_64.rpm is not signed
Package kernel-uki-virt-6.5.5-200.t2.fc38.x86_64.rpm is not signed
Package kernel-devel-matched-6.5.5-200.t2.fc38.x86_64.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED

**Comment by sharpenedblade** [comment]
Thats wierd, il try running the build script again

**Comment by sharpenedblade** [comment]
It should push the signed packages when it finishes building

**Comment by kashortiexda** [comment]
I will try in a couple of hours to allow time to build etc..
in /etc/pki/rpm-gpg/ the .pub files are different to RPM-GPG-KEY
![Screenshot from 2023-10-04 07-43-40](https://github.com/t2linux/fedora-kernel/assets/8011350/561dd71b-df97-46a1-982d-e77d59188f70)

**Comment by sharpenedblade** [comment]
its just the naming, they are both gpg files

**Comment by kashortiexda** [comment]
Updated to 6.5.5-200.fc38, now working on F39beta. THANK YOU @sharpenedblade for your patience with me, and THANK YOU for your work on these kernels, really appreciate it.
